/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <rpc/rpc.h> 
#include "rbd.h"

static int retcode; 
struct Agenda bd[100]; /* armazena o struct */ 
int  n_nomes = 0;

int *
inicializar_1_svc(void *argp, struct svc_req *rqstp)
{
	n_nomes = 0;
	retcode = 1;
    return &retcode;
}

int *
insere_1_svc(struct Agenda *a, struct svc_req *rqstp)
{
	bd[n_nomes].nome = malloc(255 * sizeof(char));
	strcpy(bd[n_nomes].nome, a->nome);
    bd[n_nomes].telefone = malloc(255 * sizeof(char));
	strcpy(bd[n_nomes].telefone, a->telefone);
	bd[n_nomes].endereco = malloc(255 * sizeof(char));
	strcpy(bd[n_nomes].endereco, a->endereco);
	bd[n_nomes].email = malloc(255 * sizeof(char));
	strcpy(bd[n_nomes].email, a->email);

    n_nomes++; 
    retcode = n_nomes;

	return &retcode;
}

int *
remove_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	int i; 
  	for (i=0; i< n_nomes; i++) {
		if (strcmp(*argp, bd[i].nome) == 0) { 
			n_nomes--; 
			bd[i] = bd[n_nomes]; 
			result = 1;
			return &result;
		} 
	}
	result = 0; 
	return &result;
}

Agenda *
busca_1_svc(char **argp, struct svc_req *rqstp)
{
	static Agenda result;
	int i; 
  	for (i=0; i< n_nomes; i++) {
		if (strcmp(*argp, bd[i].nome) == 0) { 
			result = bd[i];	
			return &result; 
		} 
	}
	result.nome = "0";
	return &result;
}

int *
numero_agenda_1_svc(void *argp, struct svc_req *rqstp)
{
	retcode = n_nomes;
	return &retcode;
}

Agenda *
listar_1_svc(int *argp, struct svc_req *rqstp)
{
	static Agenda result;
	int idx = *argp;

	result = bd[idx];
	return &result;
}
